// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ISEFinalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void iSEFinal() {
    driver.get("http://ec2-18-223-209-72.us-east-2.compute.amazonaws.com:8080/final-project/Homepage.html");
    driver.manage().window().setSize(new Dimension(1440, 780));
    driver.findElement(By.name("keyword")).click();
    driver.findElement(By.name("keyword")).sendKeys("volo");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("booktitle")).click();
    driver.findElement(By.id("booktitle")).sendKeys("The Will to Keep Winning");
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("author")).sendKeys("Daigo Umehara");
    driver.findElement(By.id("genre")).click();
    driver.findElement(By.cssSelector(".center-div:nth-child(6) > form")).click();
    driver.findElement(By.cssSelector(".center-div:nth-child(6) > form")).click();
    driver.findElement(By.id("genre")).click();
    driver.findElement(By.id("genre")).sendKeys("Autobiography");
    driver.findElement(By.cssSelector(".center-div:nth-child(6) > form")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("4758691235");
    driver.findElement(By.name("summary")).click();
    driver.findElement(By.name("summary")).sendKeys("A brief summary of the life of Daigo Umehara.");
    driver.findElement(By.cssSelector(".center-div:nth-child(6) > form")).click();
    driver.findElement(By.cssSelector("p:nth-child(14) > input")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("rate")).click();
    driver.findElement(By.id("rate")).sendKeys("5.0");
    driver.findElement(By.id("review")).click();
    driver.findElement(By.id("review")).sendKeys("Awesome book!");
    driver.findElement(By.id("keyword")).click();
    driver.findElement(By.id("keyword")).sendKeys("Daigo");
    driver.findElement(By.cssSelector("p:nth-child(12) > input")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
}
